### ISSUE TITLE
Is this middleware still usefull with dotnet core 2.2?

### ISSUE THREAD

**Issue by mlouage** [christianacca/ProblemDetailsDemo#2]
Hello

I have read that dotnet core 2.2 now supports the problem details RFC out of the box. What would be the benefit of using this library? What would I not get when only sticking to the default dotnet core implementation?

Many thanks

Maarten

**Comment by christianacca** [comment]
Hi Maarten,

I refer you to this issue asking same/similar question: https://github.com/khellang/Middleware/issues/39#issuecomment-445989073

For convenience here's the salient point (a reply from the author of the middleware):
> This middleware handles much more than what MVC does, though. It's really designed to be an exception handling middleware (that also happens to convert non-success status codes to problem details responses, like MVC 2.2 does).

**Comment by mlouage** [comment]
Clear, thanks for your reply!
